services:

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://myappdbuser:myappdbpass@db:5432/myappdb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappdbuser
      POSTGRES_PASSWORD: myappdbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myappdbuser -d myappdb -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: