version: "3.9"

services:

  web:
    image: sonofalegend/realestateapp:1.0
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://myappdbuser:myappdbpass@db:5432/myappdb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappdbuser
      POSTGRES_PASSWORD: myappdbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: